### ISSUE TITLE
Feature(s) for rcgen and ring

### ISSUE THREAD

**Issue by MOZGIII** [BiagioFesta/wtransport#103]
The version added `rcgen` and `ring` as dependencies, I'd like to avoid pulling them into my codebase.

I propose that we make them optional and add a default-on feature to enable them and the related functionality.

**Comment by BiagioFesta** [comment]
> I'd like to avoid pulling them into my codebase.
May I ask why? I am wondering if that's related with https://github.com/BiagioFesta/wtransport/issues/102 (wasm support)

`rcgen` is needed for self-signed certificate generation.
`ring` is needed for cryptographic functions (certificate signature from pub-key).

I guess I can probably put new self-signed functionality behind feature, but I would like to understand better why.

Please also note that, `ring` is a direct dependency now (as used directly), but it was already a dependency of the project since version `0.1.1`; that's because `rustls` (we depend on it) depends on `ring` anyway. Why the problem came up only now?

**Comment by BiagioFesta** [comment]
That makes sense, considering self-signed is not something one should aim to have in PROD env.

Could you please test the PR: https://github.com/BiagioFesta/wtransport/pull/107 ?

And check if that solves all your issues?

**Comment by BiagioFesta** [comment]
[As doc says](https://docs.rs/wtransport/latest/wtransport/struct.Certificate.html#method.fingerprints), this computes the "fingerprint" of the certificate: SHA265-base64 of public's key.

This indeed meant for let chrome accepting self-signed certificate. You can look at the [full.rs example](https://github.com/BiagioFesta/wtransport/blob/master/wtransport/examples/full.rs#L290-L295). This is the argument passed to google chrome (i.e., `--ignore-certificate-errors-spki-list`).

What do you mean "moving it out from wtransport"? The method is pretty simple: just using deps to compute sha256 and base64: https://docs.rs/wtransport/latest/src/wtransport/tls.rs.html#194-195

```rust
let digest = digest(&SHA256, x509_cert.public_key().raw);
                Base64Engine.encode(digest)
```

**Comment by MOZGIII** [comment]
> moving it out from wtransport

I mean literally placing it into a separate crate that does just that :D Maybe in the same repo, but just a separate crate. Actually, I think it might be a better fit for my `xwt`, since my direct goal is providing cross-platform compat, and for wasm for instance I wouldn't want to pull the whole `wtransport` for this, and this implementation is pretty simple.

The issue I had with Chrome is that I used the same method, and read the Chrome source to make sure I used the right flags - but it didn't work for whatever reason, so I just omitted the certificate specification at the client end in my web app. I was thinking it would work with certificates that don't have a full trust chain - but it seems like it doesn't do that. So I just set up ACME instead.
