### ISSUE TITLE
Feature Request: Add ability to specify headers on connect

### ISSUE THREAD

**Issue by ricky26** [BiagioFesta/wtransport#91]
At the moment, as far as I can tell, we can parse the connection request headers on the server side, but can't provide any on the client side.

**Comment by BiagioFesta** [comment]
Yes, you're right.

At the moment, the headers for the connection request are fixed: https://github.com/BiagioFesta/wtransport/blob/82a5b99b220fbd2886ab85370f815c5e33a64e2e/wtransport-proto/src/session.rs#L102-L108

Those are set in accordance with draft webtransport standard: https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3/#name-creating-a-new-session.

Therefore, these particular fields cannot/should not be changed.

However, it should still be possible to add "custom"/"additional" fields. Is that what you are looking for? May I ask about the usage scenario so that we can better define an implementation approach to fulfill your request?

**Comment by ricky26** [comment]
I was hoping to add additional headers for auth. As far as I can tell, that's still within the spec and would work for my immediate needs, however I hadn't considered the JS API (which doesn't support it), so I might have to go about this a different way anyway.

**Comment by porkiedev** [comment]
I would also love to see this feature added. I am trying to create a blazing fast and efficient real-time API, but as the API evolves, I need the Client to be able to negotiate the highest API version that it supports. Putting a version number in an HTTP request header would be a whole lot easier than creating a dedicated WebTransport tunnel for API version negotiation.

I'm happy to help in any way I can!

**Comment by BiagioFesta** [comment]
Feature implemented here: https://github.com/BiagioFesta/wtransport/pull/97
