### ISSUE TITLE
Create wtransport::Certificate directly from rcgen::Certificate

### ISSUE THREAD

**Issue by cBournhonesque** [BiagioFesta/wtransport#96]
I am writing a test, where I need to pass in a `wtransport::Certificate` to the `ServerConfig`.

I wanted to generate the `wtransport::Certificate` on the fly by calling (copied from your `gencert.rs` example)
```
const COMMON_NAME: &str = "localhost";

let mut dname = DistinguishedName::new();
dname.push(DnType::CommonName, COMMON_NAME);

let keypair = KeyPair::generate(&PKCS_ECDSA_P256_SHA256).unwrap();

let digest = digest(&SHA256, &keypair.public_key_der());

let mut cert_params = CertificateParams::new(vec![COMMON_NAME.to_string()]);
cert_params.distinguished_name = dname;
cert_params.alg = &PKCS_ECDSA_P256_SHA256;
cert_params.key_pair = Some(keypair);
cert_params.not_before = OffsetDateTime::now_utc()
    .checked_sub(Duration::days(2))
    .unwrap();
cert_params.not_after = OffsetDateTime::now_utc()
    .checked_add(Duration::days(2))
    .unwrap();

let certificate = rcgen::Certificate::from_params(cert_params).unwrap();
```
and then converting the `rcgen::Certificate`, but I could not find an easy way to convert the `rcgen::Certificate` into a `wtransport::Certificate` apart from creating `cert.pem` and `key.pem` files.
This is slightly unwieldy for tests as I have to remember to delete those files after running the tests; maybe there could be a way to make this conversion without saving the certificate to local files?

**Comment by BiagioFesta** [comment]
Sure.

That's actually performed in the [`examples/full.rs`](https://github.com/BiagioFesta/wtransport/blob/master/wtransport/examples/full.rs#L82-L83).

Once you have your `rcgen::Certificate`, you can use [`serialize_der`](https://docs.rs/rcgen/latest/rcgen/struct.Certificate.html#method.serialize_der) and [`serialize_private_key_der`](https://docs.rs/rcgen/latest/rcgen/struct.Certificate.html#method.serialize_private_key_der) to obtain the bytes of the certificate and private key in the *DER* form.

`wtransport::Certificate` allows you to create a new certificate starting from those bytes (instead of reading from file) with: [Certificate::new](https://docs.rs/wtransport/latest/wtransport/tls/struct.Certificate.html#method.new):
```rust
 let certificate = Certificate::new(
       vec![rcgen_certificate.certificate_der().to_vec()],
           rcgen_certificate.private_key_der().to_vec(),
      );
```

**Comment by cBournhonesque** [comment]
oh awesome! thanks

**Comment by BiagioFesta** [comment]
Thanks to your feedback, I thought it was a good idea to have a simple method for generating self-signed certificate directly from the library.

I've opened: https://github.com/BiagioFesta/wtransport/pull/100

This allows simply generating  self-signed certificate:
```rust
use wtransport::tls::Certificate;

let certificate = Certificate::self_signed();
```

I am going to close this issue.

Thank you
